feat: add getRipeWhiteAdminOptions
ripe-tech/ripe-commons-js pull request #39
Opened 2022-05-25 11:23 UTC by joaofsl

| - | - |
| --- | --- |
| Issue | Originated in the discussion of https://github.com/ripe-tech/ripe-util-vue/issues/267 in https://github.com/ripe-tech/ripe-util-vue/pull/281#discussion_r880553385 |

2022-05-27 17:31 UTC, joamag requested changes

2022-05-27 17:31 UTC, joamag commented on test/env.js
> +describe("Env", () => {
we're not using arrow functions for the unit tests

2022-05-30 08:57 UTC, beneditomauro commented on test/env.js
> +    describe("#getRipeWhiteAdminOptions()", () => {
Okay, I will do this in a different PR

2022-05-31 15:54 UTC, joao-conde requested changes

2022-05-31 15:54 UTC, joao-conde commented on test/env.js
> +            const nowBrunchEnvOptions = ripeCommons.getRipeWhiteAdminOptions("now-branch");
Im hungry too, but I think this should be `nowBranchEnvOptions`

2022-05-31 15:54 UTC, joao-conde commented on test/env.js
> +        it("should return fallback options when environment different than 'ci', 'test', 'stage' and 'production' ", function() {
Write a similar test but when the fallback is something else than {}

2022-05-31 15:54 UTC, joao-conde commented on test/env.js
> +describe("Env", () => {
Regular function too instead of arrow

2022-05-31 15:54 UTC, joao-conde commented on test/env.js
> +const ripeCommons = require("..");
new line between 3rd party and our packages

2022-06-06 08:22 UTC, joao-conde approved these changes

2022-06-06 09:56 UTC, BeeMargarida approved these changes

2022-06-06 14:35 UTC, joamag approved these changes

2022-06-07 09:01 UTC, joamag approved these changes

2022-06-07 09:01 UTC, merged